import type { RangeResult } from "./random";

// The below tables are ©2017 Sine Nomine Publishing, Inc.
// Taken from Stars Without Number Revised Free Edition, available here:
// https://www.drivethrurpg.com/en/product/230009/stars-without-number-revised-edition-free-version

// 2d6
export const AtmosphereTable: RangeResult<string>[] = [
  { min: 2, max: 2, result: "Corrosive, damaging to foreign objects" },
  { min: 3, max: 3, result: "Inert gas, useless for respiration" },
  { min: 4, max: 4, result: "Airless or thin to the point of suffocation" },
  { min: 5, max: 9, result: "Breathable mix" },
  { min: 10, max: 10, result: "Thick, but breathable with a pressure mask" },
  { min: 11, max: 11, result: "Invasive, penetrating suit seals" },
  { min: 12, max: 12, result: "Both corrosive and invasive in its effects" },
];

// 2d6
export const TemperatureTable: RangeResult<string>[] = [
  { min: 2, max: 2, result: "Frozen, locked in perpetual ice" },
  { min: 3, max: 3, result: "Cold, dominated by glaciers and tundra" },
  { min: 4, max: 5, result: "Variable cold with temperate places" },
  { min: 6, max: 8, result: "Temperate, Earthlike in its ranges" },
  { min: 9, max: 10, result: "Variable warm, with temperate places" },
  { min: 11, max: 11, result: "Warm, tropical and hotter in places" },
  { min: 12, max: 12, result: "Burning, intolerably hot on its surface" },
];

// 2d6
export const BiosphereTable: RangeResult<string>[] = [
  { min: 2, max: 2, result: "Remnant biosphere" },
  { min: 3, max: 3, result: "Microbial life forms exist" },
  { min: 4, max: 5, result: "No native biosphere" },
  { min: 6, max: 8, result: "Human-miscible biosphere" },
  { min: 9, max: 10, result: "Immiscible biosphere" },
  { min: 11, max: 11, result: "Hybrid biosphere" },
  { min: 12, max: 12, result: "Engineered biosphere" },
];

// 2d6
export const PopulationTable: RangeResult<string>[] = [
  { min: 2, max: 2, result: "Failed colony" },
  { min: 3, max: 3, result: "Outpost" },
  { min: 4, max: 5, result: "Fewer than a million inhabitants" },
  { min: 6, max: 8, result: "Several million inhabitants" },
  { min: 9, max: 10, result: "Hundreds of millions of inhabitants" },
  { min: 11, max: 11, result: "Billions of inhabitants" },
  { min: 12, max: 12, result: "Alien inhabitants" },
];

// 2d6
export const TechLevelTable: RangeResult<string>[] = [
  { min: 2, max: 2, result: "TL0, neolithic-level technology" },
  { min: 3, max: 3, result: "TL1, medieval technology" },
  { min: 4, max: 5, result: "TL2, early Industrial Age tech" },
  { min: 6, max: 8, result: "TL4, modern postech" },
  { min: 9, max: 10, result: "TL3, tech like that of present-day Earth" },
  { min: 11, max: 11, result: "TL4+, postech with specialties" },
  { min: 12, max: 12, result: "TL5, pretech with surviving infrastructure" },
];

export const WorldTags: string[] = [
  "Abandoned Colony",
  "Alien Ruins",
  "Altered Humanity",
  "Anarchists",
  "Anthropomorphs",
  "Area 51",
  "Badlands World",
  "Battleground",
  "Beastmasters",
  "Bubble Cities",
  "Cheap Life",
  "Civil War",
  "Cold War",
  "Colonized Population",
  "Cultural Power",
  "Cybercommunists",
  "Cyborgs",
  "Cyclical Doom",
  "Desert World",
  "Doomed World",
  "Dying Race",
  "Eugenic Cult",
  "Exchange Consulate",
  "Fallen Hegemon",
  "Feral World",
  "Flying Cities",
  "Forbidden Tech",
  "Former Warriors",
  "Freak Geology",
  "Freak Weather",
  "Friendly Foe",
  "Gold Rush",
  "Great Work",
  "Hatred",
  "Heavy Industry",
  "Heavy Mining",
  "Hivemind",
  "Holy War",
  "Hostile Biosphere",
  "Hostile Space",
  "Immortals",
  "Local Specialty",
  "Local Tech",
  "Major Spaceyard",
  "Mandarinate",
  "Mandate Base",
  "Maneaters",
  "Megacorps",
  "Mercenaries",
  "Minimal Contact",
  "Misandry/Misogyny",
  "Night World",
  "Nomads",
  "Oceanic World",
  "Out of Contact",
  "Outpost World",
  "Perimeter Agency",
  "Pilgrimage Site",
  "Pleasure World",
  "Police State",
  "Post-Scarcity",
  "Preceptor Archive",
  "Pretech Cultists",
  "Primitive Aliens",
  "Prison Planet",
  "Psionics Academy",
  "Psionics Fear",
  "Psionics Worship",
  "Quarantined World",
  "Radioactive World",
  "Refugees",
  "Regional Hegemon",
  "Restrictive Laws",
  "Revanchists",
  "Revolutionaries",
  "Rigid Culture",
  "Rising Hegemon",
  "Ritual Combat",
  "Robots",
  "Seagoing Cities",
  "Sealed Menace",
  "Secret Masters",
  "Sectarians",
  "Seismic Instability",
  "Shackled World",
  "Societal Despair",
  "Sole Supplier",
  "Taboo Treasure",
  "Terraform Failure",
  "Theocracy",
  "Tomb World",
  "Trade Hub",
  "Tyranny",
  "Unbraked AI",
  "Urbanized Surface",
  "Utopia",
  "Warlords",
  "Xenophiles",
  "Xenophobes",
  "Zombies",
]

export const Backgrounds: string[] = [
  "Barbarian",
  "Clergy",
  "Courtesan",
  "Criminal",
  "Dilettante",
  "Entertainer",
  "Merchant",
  "Noble",
  "Official",
  "Peasant",
  "Physician",
  "Pilot",
  "Politician",
  "Scholar",
  "Soldier",
  "Spacer",
  "Technician",
  "Thug",
  "Vagabond",
  "Worker",
]
